name: flymedia_app
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  background_downloader: ^8.0.5
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.13.6
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2
  easy_refresh: ^3.3.2+1
  emoji_picker_flutter: ^1.6.3
  equatable: ^2.0.5
  file_picker: ^6.1.1
  file_selector_macos: ^0.9.3+3
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.6
  firebase_ui_firestore: ^1.5.15
  fluentui_icons: ^1.0.0
  flutter:
    sdk: flutter
  flutter_chat_bubble: ^2.0.2
  flutter_file_dialog: ^3.0.2
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  flutter_tawk: ^0.1.0
  flutter_vector_icons: ^2.0.0
  font_awesome_flutter: ^10.5.0
  form_validators:
    path: packages/form_validators
  get: ^4.6.6
  google_fonts: ^4.0.3
  google_sign_in: ^6.1.5
  http: ^1.1.0
  image_cropper: ^5.0.1
  image_picker: ^1.0.4
  intl: ^0.18.1
  loading_animation_widget: ^1.2.0+4
  loading_overlay: ^0.3.0
  lottie: ^2.7.0
  objectid: 2.0.0
  path_provider: ^2.1.1
  pinput: ^3.0.1
  provider: ^6.1.1
  pull_to_refresh: ^2.0.0
  rive: ^0.12.3
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  sign_in_with_apple: ^5.0.0
  smooth_page_indicator: ^1.1.0
  unicons: ^2.1.1
  uuid: ^3.0.7
  webview_flutter: ^3.0.4
  webview_flutter_wkwebview: ^2.9.5
  zoom_tap_animation: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/rive_assets/
    - assets/images/cell.svg
    - assets/images/Ellipse16.svg
    - assets/images/firstOnboardEllipes.svg
    - assets/images/handshake.svg
    - assets/images/lineOnboard.svg
    - assets/images/sophieEllipse.svg
    - assets/images/verifyEmail.svg
    - assets/images/onboardSvg.svg
    - assets/countrY_list.json

  fonts:
    - family: Karla
      fonts:
        - asset: assets/fonts/karla.regular.ttf
