name: flymedia_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  file_selector_macos: ^0.9.3+3
  fluentui_icons: ^1.0.0
  flutter:
    sdk: flutter
  flutter_chat_bubble: ^2.0.2
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  flutter_vector_icons: ^2.0.0
  font_awesome_flutter: ^10.5.0
  form_validators:
    path: packages/form_validators
  get: ^4.6.6
  google_fonts: ^4.0.3
  google_sign_in: ^6.1.5
  http: ^1.1.0
  image_cropper: ^5.0.1
  image_picker: ^1.0.4
  loading_animation_widget: ^1.2.0+4
  loading_overlay: ^0.3.0
  objectid: 2.0.0
  path_provider: ^2.1.1
  pinput: ^3.0.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  unicons: ^2.1.1
  uuid: ^3.0.7
  webview_flutter: ^4.2.4
  zoom_tap_animation: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/cell.svg
    - assets/images/Ellipse16.svg
    - assets/images/firstOnboardEllipes.svg
    - assets/images/handshake.svg
    - assets/images/lineOnboard.svg
    - assets/images/sophieEllipse.svg
    - assets/images/verifyEmail.svg
    - assets/images/onboardSvg.svg
    - assets/countrY_list.json

  fonts:
    - family: Karla
      fonts:
        - asset: assets/fonts/karla.regular.ttf
